# This file was generated by GoReleaser. DO NOT EDIT.
cask "supawho" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "a8cab3c81e8bdb25d1ca86e90923817f8dd4dcd68a25cfb3a06875c5760a9281"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "afee985923055c920a7d1840715d8855bbaaa282e4d51cdb71b5a4823342f79c"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05c14ff03227c2f9713397c235140852ed9dcb38b8b42880b24077a6621f6a10"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "71912933f3d14e3a51ec650f5091fee44172d13c7ac0495ea5542e7246b46af3"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "supawho"
  desc "Manage multiple Supabase CLI accounts securely across macOS, Linux and Windows"
  homepage "https://github.com/EliaTolin/supawho"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "supawho"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/supawho"]
    end
  end

  # No zap stanza required

end
