# This file was generated by GoReleaser. DO NOT EDIT.
cask "supawho" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "3ee27d0624cdeb5fe6b0f46e6d70e0fc1b7614ca235979389ab9e141e6b907f5"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "61ce86c3b89120fef3be1920d78892d2b62f3d1620c6489ee8c73e5ecb20f00e"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba17ead864d24a977da7853d1a04c0d43977cd3aa0ec051715ef3c2bb5987d9d"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "772f6a428850ab25240ada2a92cee7bb1b34c3e6247870ed560eafb65f1f2b22"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "supawho"
  desc "Manage multiple Supabase CLI accounts securely across macOS, Linux and Windows"
  homepage "https://github.com/EliaTolin/supawho"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "supawho"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/supawho"]
    end
  end

  # No zap stanza required

end
