# This file was generated by GoReleaser. DO NOT EDIT.
cask "supawho" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "7548c2b56b1baa3aba326447ef05d46844fb5335677b9aa591b698de78ae5620"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1a17cfdbfe53933f258198c9e5c0a202e264d708035030dd7de709e7c192af74"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d92d06191480caf66f90898567ea8b6cb8450dd029b05332ecf2c31261c1d4fe"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "51c4f0c17c1fdb977715317404460efd4162ac0f8f75f3a9fdd57a643152b5ad"
      url "https://github.com/EliaTolin/supawho/releases/download/v#{version}/supawho_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "supawho"
  desc "Manage multiple Supabase CLI accounts securely across macOS, Linux and Windows"
  homepage "https://github.com/EliaTolin/supawho"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "supawho"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/supawho"]
    end
  end

  # No zap stanza required

end
